config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  root 'items#index'
  get 'edit' => 'users#edit'

  resources :users, only: [:show, :new, :edit, :update] do
    resources :cards, only: [:index, :new] do
      # cards controllerはモデルを持たない。データはpayjpに格納
      member do
        get 'pay' #カード決済アクション
        get 'card_delete'
        get 'card_new' #カード登録アクション(newとは違いviewを持たない)
      end
    end
    collection do
      get 'signup/:url',action: 'new'
      get 'mypage/:url',action: 'edit'
    end
  end

  resources :items do
    member do
      get 'confirm' #購入確認画面
    end
    collection do
      get 'search'
    end
    resources :categories, only: [:search]
  end

  resources :categories, only: :show
end

app/views/shared/_aside.html.haml
%aside.app-banner
  .pc-app-banne
    .pc-app-banner__inner
      =image_tag "aside-image.png"
      
    -# 以下は、余裕があったら作る
    -#   %h2 スマホでかんたんフリマアプリ
    -#   %p 今すぐ無料ダウンロード！
    -# .pc-app-banner__icon__list.clearfix
    -#   %figure
    -#     =image_tag "mercari_icon.png", size:"68", alt:""
    -#   %ul.clearfix
    -#     %li
    -#       =link_to 'アップルストアへのリンク', src: "#", target: "_blank" do
    -#         -# =image_tag "ファイル名", size:"133X40", alt:""
    -#     %li
    -#       =link_to 'googleストアへのリンク', src: "#", target: "_blank" do
    -#         -# =image_tag "ファイル名", size:"133X40", alt:""
    -#   %figure
    -#     -# =image_tag 'スマホの写真', src: "#", alt:""

app/views/shared/_breadcrumb.html.haml
%nav.breadcrumb-container
  .breadcrumb
    = breadcrumbs separator: "#{content_tag(:span, '', :class=>'icon-arrow-r')}", class:"breadcrumb__list"

app/views/shared/_category-list.html.haml
- parents = @categories[0..12]
.category-list
  %ul.category-list__parent
    - parents.each do |parent|
      %li= link_to parent.name, category_path(id: parent.id), data: {parent: parent.id}
  - parents.each do |parent|
    %ul.category-list__child{id: "#{parent.id}-children"}
      - parent.children.each do |child|
        %li= link_to child.name, category_path(id: child.id), data: {child: child.id}
  - parents.each do |parent|
    - parent.children.each do |child|
      %ul.category-list__grandchild{id: "#{child.id}-grandchildren"}
        - child.children.each do |grandchild|
          %li= link_to grandchild.name, category_path(id: grandchild.id)

app/views/shared/_footer-sell-btn.html.haml
.footer_sell_btn
  = link_to new_item_path do
    %p.footer_sell_btn__litter 出品
    %p.icon-camera

app/views/shared/_footer.html.haml
%footer.footer
  %nav.contents-box
    .contents-box__content
      %h2.contents-box__content__header メルカリについて
      %ul
        %li= link_to '会社概要（運営会社）', href:"#"
        %li= link_to '採用情報', href:"#"
        %li= link_to 'プレスリリース', href:"#"
        %li= link_to '公式ブログ', href:"#"
        %li= link_to 'メルカリロゴ利用ガイドライン', href:"#"
        %li.contents-box__content__social-link
          =link_to '#', target:"_blank" do
            %i.icon-twitter
        %li.contents-box__content__social-link
          =link_to '#', target:"_blank" do
            %i.icon-facdebook

    .contents-box__content
      %h2.contents-box__content__header ヘルプ＆ガイド
      %ul
        %li= link_to 'メルカリガイド', href:"#"
        %li= link_to 'らくらくメルカリ便', href:"#"
        %li= link_to 'ゆうゆうメルカリ便', href:"#"
        %li= link_to '大型メルカリ便', href:"#"
        %li= link_to '車体取引ガイド', href:"#"
        %li= link_to 'メルカリあんしん・あんぜん宣言！', href:"#"
        %li= link_to '偽ブランド品撲滅への取り組み', href:"#"
        %li= link_to 'メルカリボックス', href:"#"

    .contents-box__content.full-width
      %h2.contents-box__content__header プライバシーと利用規約
      .contents-box__content__inner
        %ul
          %li= link_to 'プライバシーポリシー', href:"#"
          %li= link_to 'メルカリ利用規約', href:"#"
          %li= link_to 'あんしんスマホサポート制度に関する利用特約', src:"#"
          %li= link_to 'コンプライアンスポリシー', href:"#"
      .contents-box__content__inner
        %ul
          %li= link_to '個人データの安全管理に係る基本方針', href:"#"
          %li= link_to '特定商取引に関する表記', href:"#"
          %li= link_to '資金決済法に基づく表示', href:"#"
          %li= link_to '法令順守と犯罪抑止のために', href:"#"
          %li= link_to '返品・返金ポリシー', href:"#"

    .contents-box__content.footer-nav-lang
      %h2.contents-box__content__header 国
      %ul
        %li= link_to '日本', href:"#"
        %li= link_to 'United States', href:"#"

  .contents-box__bottom
    =link_to '白黒のロゴ', class: '.groval-footer__bottom__logo' do
      =image_tag "logo-white.svg", size: "124x33", alt: "mercari"
    %span.footer-copyright
      %small © 2019 Mercari

app/views/shared/_header.html.haml
%header.sp-header.visible-sp
  .sp-header__content
    %h1.sp-header__content__logo
      = link_to root_path do
        = image_tag "logo.svg", alt: 'mercari', size:"134x36"

    - if user_signed_in?
      .sp-header__user-nav
        %ul.sp-header__user-nav
          %li.sp-header__user-nav__list.icon-bell
            = link_to '', src: '#', class: 'sp-header__user-icon'

          %li.sp-header__user-nav__list.icon-check
            = link_to '', src: '#', class: 'sp-header__user-icon'

          %li.sp-header__user-nav__list
            = link_to user_path(id: 'mypage'), class: 'sp-header-user-icon user-profile__avatar' do
              = image_tag 'avatar.jpg', alt: 'プロフィール写真', width: 32

      .header__search-bar
        = form_with url: search_items_path(:keyword), method: :get, local: true do |f|
          = f.text_field :keyword, { placeholder: "何をお探しですか？", class: "header__search-bar__search"}
          = f.submit class: "search-btn", value: ""
        %p.icon-search

      %ul.header__nav
        %li.header__nav__list.icon-list
          = link_to 'カテゴリー一覧', src: '#'

        %li.header__nav__list.icon-tag
          = link_to 'ブランドから探す', src: '#'
    - else
      %ul.header__user-btn
        %li.header__user-btn__sign-in
          =link_to 'ログイン', new_user_session_path
        %li.header__user-btn__registration
          =link_to '新規会員登録', new_user_path

%header.pc-header.visible-pc
  .pc-header__inner
    .pc-header__top-content
      %h1.pc-header__top-content__logo
        = link_to root_path do
          = image_tag "logo.svg", alt: 'mercari', width: 134, height: 36

      .header__search-bar
        = form_with url: search_items_path(:keyword), method: :get, local: true do |f|
          = f.text_field :keyword, { placeholder: "何をお探しですか？", class: "header__search-bar__search"}
          = f.submit class: "search-btn", value: ""
        %p.icon-search

    .pc-header__nav__box
      .pc-header__nav__list-l
        %ul.header__nav
          %li.header__nav__list.category-show.icon-list カテゴリーから探す
          = render 'shared/category-list'
          %li.header__nav__list.bland-list.icon-tag ブランドから探す

      .pc-header__nav__list-r
        - if user_signed_in?
          %ul.pc-header__user-nav
            %li.pc-header__user-nav__list#notification-list__root.icon-bell= link_to 'お知らせ', src: '#'
            %ul#notification-list.user-box
              %li.pc-header__notification-list__link
                .merucari-avatar
                %figure
                  =image_tag 'mercari_profile.png', alt: "icon"
                .notification-box.icon-arrow-r
                  %p.notification-box__message お知らせ１
                  %p.notification-box__date-passed.icon-clock 1日前
              %li.pc-header__notification-list__link
                .merucari-avatar
                %figure
                  =image_tag 'mercari_profile.png', alt: "icon"
                .notification-box.icon-arrow-r
                  %p.notification-box__message お知らせ１
                  %p.notification-box__date-passed.icon-clock 1日前
              %li.pc-header__notification-list__link
                %figure
                  =image_tag 'mercari_profile.png', alt: "icon"
                .notification-box.icon-arrow-r
                  %p.notification-box__message お知らせ１
                  %p.notification-box__date-passed.icon-clock 1日前
              %li.pc-header__notification-list__link
                %figure
                  =image_tag 'mercari_profile.png', alt: "icon"
                .notification-box.icon-arrow-r
                  %p.notification-box__message お知らせ１
                  %p.notification-box__date-passed.icon-clock 1日前


            %li.pc-header__user-nav__list#todo-list__root.icon-check= link_to 'やることリスト', src: '#'
            .user-box#todo-list.todo-list
              .todo-list__icon__not-found
              %p.todo-list__message 現在、やることリストはありません

            %li.pc-header__user-nav__list#mypage-box__root
              = link_to user_path(id: 'mypage'), class: 'user-profile__avatar' do
                = image_tag 'avatar.jpg', alt: 'プロフィール写真', width: 32
                %span{style: "display:inline-block; height: 40px;"} マイページ
            #mypage-box
              .mypage-box
                .mypage-box__bg-image
                  %figure
                    = image_tag 'avatar.jpg', alt: 'プロフィール写真', width: 60
                .mypage-box__upper-info
                  %p.user-name= current_user.name

                  %ul.review-list
                    %li
                      = link_to '出品数： **', src: '#'
                    %li
                      = link_to '評価： **', src: '#'

                  %ul.currency
                    %li.currency__money
                      = link_to '売上金', href:'#' do
                        %ul.currency__inner__list
                          %li 売上金
                          %li.icon-arrow-r ¥ 0,000

                    %li.currency__point
                      = link_to 'ポイント', href:'#' do
                        %ul.currency__inner__list
                          %li ポイント
                          %li.icon-arrow-r 0 P

                %ul.mypage-list
                  %li.mypage-list__item.icon-arrow-r
                    = link_to '#' do
                      %p いいね！一覧
                  %li.mypage-list__item.icon-arrow-r
                    = link_to '#' do
                      %p 出品した商品 - 出品中
                  %li.mypage-list__item.icon-arrow-r
                    = link_to '#' do
                      %p 出品した商品 - 取引中
                  %li.mypage-list__item.icon-arrow-r
                    = link_to '#' do
                      %p 出品した商品 - 売却済
                  %li.mypage-list__item.icon-arrow-r
                    = link_to '#' do
                      %p 購入した商品 - 取引中
                  %li.mypage-list__item.icon-arrow-r
                    = link_to '#' do
                      %p 購入した商品 - 過去の取引
        - else
          %ul.header__user-btn
            %li.header__user-btn__sign-in
              =link_to 'ログイン', new_user_session_path
            %li.header__user-btn__registration
              =link_to '新規会員登録', new_user_path

app/views/shared/_items-box.html.haml
.item-box__container
  - items.each do |item|
    %section.item-box
      = link_to item_path(id: item.id) do
        = image_tag item.images[0].image.to_s, class: 'item-box__photo'
        -if item.status == "soldout"
          .soldout
        .visible-small-and-sp-only
          %p= "¥ #{item.price}"
        .item-box__info
          .item-box__gradient
          %h3.item-box__info__name
            = item.name
          .item-box__bottom
            %p.item-box__bottom__price
              ¥
              = item.price
            %p.item-box__bottom__like.icon-like 1
            %p.item-box__bottom__tax (税込)

app/views/shared/_mypage-nav.html.haml
.mypage-nav
  %ul
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'マイページ',user_path(id: 'mypage')
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'お知らせ','#'
      %span.mypage-nav__list__inner__num 99
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'やることリスト','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'いいね！一覧','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '出品する', new_item_path
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '出品した商品 - 出品中','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '出品した商品 - 取引中','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '出品した商品 - 売却済み','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '購入した商品 - 取引中','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '購入した商品 - 過去の取引','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'ニュース一覧','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '評価一覧','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'ガイド','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'お問い合わせ','#'

  %h3.mypage-nav__head メルペイ
  %ul
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '売上・振込申請','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'ポイント','#'

  %h3.mypage-nav__head 設定
  %ul
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      = link_to "プロフィール", edit_path(url: 'profile')
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '発送元・お届け先住所変更','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '支払い方法', user_cards_path(user_id: 'mypage')
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to 'メール/パスワード','#'
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      = link_to "本人情報", edit_path(url: 'identification')
    %li.mypage-nav__list
      .mypage-nav__list__inner.icon-arrow-r
      =link_to '電話番号の確認','#'
    %li.mypage-nav__list.mypage-nav__current-page
      .mypage-nav__list__inner.icon-arrow-r
      = link_to "ログアウト", edit_path(url: 'logout')

app/views/shared/_notification-todo.html.haml
-# NOTE: 当初設計では運営からのお知らせデータが存在しない、ダミー作成 ⇨余裕できたらデータテーブルごと追加で実装
%section.mypage-tab-container.notification-todo
  %ul.mypage-tabs
    -# TODO: .activeをjsでつけ変えることで表示を変える
    %li.active
      %h3
        -# TODO: 後回し、ページ内リンクを生成したいがうまくいかず、遷移を伴ってしまう。
        -# オリジナルではページ内リンクが設定されているものの、実際にはページ内の移動さえ起こらない、原理不明
        = link_to "お知らせ", user_path(anchor: "mypage-tab__notification")
    %li
      %h3
        -# TODO: 後回し、なぜかactiveでないこちらは遷移が発生しない、この動きをactiveにも実現したい。
        = link_to "やることリスト", user_path(anchor: "mypage-tab__todo")
  .tab-content
    -# TODO:.activeをjsでつけ変えることで表示を変える
    %ul#mypage-tab__notification.mypage-item-list.tab-pane.active

      -# TODO: - if hoges.length == 0
      -# %li.mypage-item-not-found.bold お知らせの商品がありません
      -# TODO: 最低要件はダミー表示コピーで実現する
      -# - else
      -# - hoges.foreach do |hoge|、あるいは render partial: hoges, locals {hoge: hoge}
      %li
        -# オリジナルは「ニュース一覧」へリンクする。作成優先度最低レベル。
        = link_to "#", class: "mypage-item-link" do
          %figure
            = image_tag "mercari_profile.png", size: "48x48"
          .mypage-item-body
            .mypage-item-text 事務局から個別メッセージ「ログイン通知」
            %time
              %i.icon-clock
              %span 11 時間前
          %i.icon-arrow-r

      %li
        = link_to "#", class: "mypage-item-link" do
          %figure
            = image_tag "mercari_profile.png", size: "48x48"
          .mypage-item-body
            .mypage-item-text 事務局から個別メッセージ「ログイン通知」
            %time
              %i.icon-clock
              %span 11 時間前
          %i.icon-arrow-r

      %li.mypage-go-list
        -# TODO: viewに適したパスに直す
        = link_to "一覧を見る", {controller: "users", action: "show"}

    %ul#mypage-tab__todo.mypage-item-list.tab-pane
      %li.mypage-item-not-found.bold 現在、やることリストはありません

app/views/shared/_single-footer.html.haml
%footer.single-footer
  %ul.single-footer__menu
    %li.single-footer__menu__privacy
      = link_to "プライバシーポリシー", src: "#"
    %li.single-footer__menu__terms
      = link_to "メルカリ利用規約", src: "#"
    %li.single-footer__menu__notation
      = link_to "特定商取引に関する表記", src: "#"
  .single-footer__logo
    = link_to root_path do
      = image_tag 'logo-gray.svg', height:'65px'
  .single-footer__small-text
    %small © 2019 Mercari

app/views/shared/_single-header.html.haml
%header.single-header
  =link_to root_path,class:"single-header__logo" do
    = image_tag 'logo.svg', height:'49px'

app/views/shared/_transaction-now-old.html.haml
%section.mypage-tab-container.transaction-now-old
  %h2.mypage-tab-head 購入した商品
  %ul.mypage-tabs
    -# TODO:.activeをjsでつけ変えることで表示を変える
    %li.active
      %h3
        -# TODO: notificaation-todoと同様
        = link_to "取引中", user_path(anchor: "mypage-tab__transaction-now"), data: {toggle: "tab"}
    %li
      %h3
        -# TODO: notificaation-todoと同様
        = link_to "過去の取引", user_path(anchor: "mypage-tab__transaction-old"), data: {toggle: "tab"}
  .tab-content
    -# TODO:.activeをjsでつけ変えることで表示を変える
    %ul#mypage-tab__transaction-now.mypage-item-list.tab-pane.active
      -# TODO: - if hoges.length == 0
      %li.mypage-item-not-found.bold 取引中の商品がありません

      -# TODO: 最低要件はダミー表示コピーで実現する
      -# このリストの表示がソースコピペ元のnotificationとどう違うかは不明。
      -# - else
      -# - hoges.foreach do |hoge|、あるいは render partial: hoges, locals {hoge: hoge}
      -# %li
      -#   = link_to "#", class: mypage-item-link
      -#     %figure
      -#       = image_tag "mercari_profile.png", size: "48x48"
      -#     .mypage-item-body
      -#       .mypage-item-text 事務局から個別メッセージ「ログイン通知」
      -#       %time
      -#         %i.icon-time
      -#         %span 11 時間前
      -#     %i.icon-arrow-right
      -# %li.mypage-go-list
      -#   TODO: viewに適したパスに直す
      -#   = link_to "一覧を見る", {controller: "users", action: "show"}
    %ul#mypage-tab__transaction-old.mypage-item-list.tab-pane
      %li.mypage-item-not-found.bold 過去に取引した商品がありません

app/views/shared/_upload-images.haml
.upload-item
  = image_tag image.image.url, class: "upload-item__photo"
  .upload-item__nav
    .upload-item__nav__edit
      %p 編集
    = f.label :remove_image[i], class: "upload-item__nav__delete" do
      = f.check_box :remove_image[i], class: "hidden delete-check-box check-box"
      %p 削除