config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  root 'items#index'
  get 'edit' => 'users#edit'

  resources :users, only: [:show, :new, :edit, :update] do
    resources :cards, only: [:index, :new] do
      # cards controllerはモデルを持たない。データはpayjpに格納
      member do
        get 'pay' #カード決済アクション
        get 'card_delete'
        get 'card_new' #カード登録アクション(newとは違いviewを持たない)
      end
    end
    collection do
      get 'signup/:url',action: 'new'
      get 'mypage/:url',action: 'edit'
    end
  end

  resources :items do
    member do
      get 'confirm' #購入確認画面
    end
    collection do
      get 'search'
    end
    resources :categories, only: [:search]
  end

  resources :categories, only: :show
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :user_items, dependent: :destroy
  has_many :users, through: :user_items
  has_many :images, dependent: :destroy
  belongs_to :category

  accepts_nested_attributes_for :images, allow_destroy: true



  # TODO: カテゴリ実装時、特定カテゴリが入力された場合のみ:sizeが必須となる条件
  with_options presence: true do
    validates :name, length: {maximum: 40}
    validates :detail, length: {maximum: 1000}
    validates :condition
    validates :delivery_method
    validates :delivery_prefecture
    validates :delivery_day
    validates :price, numericality: {greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  end

  enum condition: {
    new_one: 1, almost_new: 2, no_scratchies: 3, little_worn: 4, worn: 5, bad: 6
  }

  enum delivery_cost: {
    exhibitr_barden: 1, buyer_barden: 2
  }

  enum delivery_day: {
    a_day: 1, a_couple_of_days: 2, a_week: 3
  }

  enum delivery_prefecture: {
    hokkaido: 1, aomori: 2, iwate: 3, miyagi: 4, akita: 5, yamagata: 6, fukushima: 7,
    ibaraki: 8, tochigi: 9, gunma: 10, saitama: 11, chiba: 12, tokyo: 13, kanagawa: 14,
    nigata: 15, toyama: 16, ishikawa: 17, fukui: 18, yamanashi: 19, nagano: 20,
    gifu: 21, sizuoka: 22, aichi: 23, mie: 24,
    shiga: 25, kyoto: 26, osaka: 27, hyogo: 28, nara: 29, wakayama: 30,
    tottori: 31, shimane: 32, okayama: 33, hiroshima: 34, yamaguchi: 35,
    tokushima: 36, kagawa: 37, ehime: 38, kochi: 39,
    fukuoka: 40, saga: 41, nagasaki: 42, kumamoto: 43, oita: 44, miyazaki: 45, kagoshima: 46, okinawa: 47,
    undicided: 48
  }, _prefix: true

  enum delivery_method: {
    undicided: 1, mercari: 2, u_mail: 3, letter_pack: 4, usealy: 5, yamato: 6, u_pack: 7, click_post: 8, u_packet: 9
  }, _prefix: true

  enum status: {
    not_sale: 0, sale:1, soldout:2
  }, _prefix: true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  require 'payjp'
  before_action :set_item, only: [:show, :destroy, :edit, :confirm, :pay, :update]
  before_action :set_categories, only: [:index, :show, :search, :new, :create, :edit]
  before_action :authenticate_user!, only: [:new, :create, :confirm, :edit, :destroy]

  def index # トップページ、アイテムをカテゴリー別に最新投稿順番に
    @ladies_items = set_category_items('レディース')
    @mens_items = set_category_items('メンズ')
    @kids_items = set_category_items('ベビー・キッズ')
    @cosme_items = set_category_items('コスメ・香水・美容')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(params_new)
    @item[:category_id] = set_items_category_id
    respond_to do |format|
      if @item.save
        # rails scaffold item で自動作成されたコントローラ記述をそのまま移植。
        # TODO: 仮置きredirect, 最終形=>newページ内でモーダル表示させる
        UserItem.create(user_id: current_user.id, item_id: @item.id)
        if params[:file]
          for i in 0..10
            Image.create(image: params[:file]["#{i}"], item_id: @item.id) if params[:file]["#{i}"] != nil
          end
        end
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        # TODO: 最終形=>入力不備label部分に赤字でガイド表示させる
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @same_user_items = Item.joins(:users).where('users.id = ? AND status = ?', @item.users[0].id, 1).where.not(id: @item.id).order(id: 'DESC').limit(6)
    category_ids = Category.find(@item.category_id).descendant_ids.push(@item.category_id)
    @same_category_items = Item.where(category_id: category_ids, status: 1).where.not(id: @item.id).order(id: 'DESC').limit(6)
  end

  def confirm
    begin
    Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]
    customer = Payjp::Customer.retrieve(current_user.payjp_id)
    default_card = customer.default_card
    @card = customer.cards.retrieve(default_card)
    rescue => e
      redirect_to item_path
    end
  end

  def edit
  end

  def update
    @item[:category_id] = set_items_category_id
    if @item.update(params_new)
      redirect_to item_path(@item)
    else
      redirect_to edit_item_path
    end
  end

  def search
    @items = Item.where('name LIKE(?)', "%#{params[:keyword]}%").limit(40)
    @all_items = Item.order(id: "DESC").limit(40)
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to item_path(@item)
    end
  end

  private

  def params_new
    params.require(:item).permit(:name, :condition, :detail, :delivery_method, :delivery_prefecture, :delivery_cost, :delivery_day, :price, images_attributes: [:image])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_category_items(name)
    category_ids = Category.find_by(name: name).descendant_ids.push(Category.find_by(name: name).id)
    return Item.where(category_id: category_ids, status: 1).order(id: "DESC").limit(4)
  end

  def set_items_category_id
    if params[:item][:grandchild_category_id].present?
      return params[:item][:grandchild_category_id]
    elsif params[:item][:child_category_id].present?
      return params[:item][:child_category_id]
    else
      return params[:item][:parent_category_id]
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_comment.html.haml
.comment
  .comment__left
    %li.sp-header__user-nav__list
      = link_to 'マイページへのリンク', src: '#', class: 'sp-header-user-icon user-profile__avatar' do
        = image_tag 'avatar.jpg', alt: 'プロフィール写真', width: 32
      -# - if ページのid = user.id
      .seller-name 出品者
  .comment__right
    .posted-name すずき
    .comment__body
      .comment__body__text こんにちは！それほしい！
      .icon
      .posted-day 1年前
  .icon-balloon

app/views/items/confirm.html.haml
.single-wrapper.buy-confirm-page
  = render 'shared/single-header'
  %main.single-container
    .panel
      %section.panel__head 購入内容の確認
      .panel__inner
        %section.buy-content
          .item-info
            %h3.item-info__image
              =image_tag  (@item.images[0].image.url), alt: '商品画像', class: "confirm-image"
            %p.item-info__name
              = @item.name
            %p.item-info__price
              ="¥#{@item.price}"
              %span.item-info__price__shipping
                = @item.delivery_cost_i18n
                -# ポイントがある場合とない場合で表示が切り替わります。余裕があれば追加
                -# %ul.buy-accordion.not-have
                -#   %li.buy-accordion__inner
                -#     .buy-accordion__accordion__toggle
                -#       %p ポイントはありません
            %ul.buy-price
              %li.buy-price__inner
                .buy-price__inner__cell 支払い金額
                .buy-price__inner__cell
                  %span{data: {price: @item.price}}
                    = "¥#{@item.price}"
              %p
                =link_to "購入する", pay_user_card_path(current_user.id), class: "buy-confirm-btn"
        %hr.line
        %section.buy-content
          .user-info
            %h3.user-info__header 配送先
            %adress.user-info__text
              %p
                = "〒#{current_user.postal_code.to_s.insert(3, '-')}"
                %br
                = "#{current_user.prefecture_i18n} #{current_user.city}"
                %br
                = current_user.address
                %br
                = current_user.building
                %br
                =current_user.name

              %p.link-to-change.icon-arrow-r
                =link_to "変更する", edit_path(url:"identification")

          -# 支払い情報がnillだとグレーのボタンとなり購入できないが、とりあえず無視する
          %hr.line
          .card-info
            %h3.card-info__header 支払い方法
            %p.card-info__num
              = "**** **** **** #{@card.last4}"
            %p.card-info__date
              = "#{@card.exp_month} / #{@card.exp_year}"

            %p.link-to-change.icon-arrow-r
              -# =link_to "変更する", user_card_path(user_id:'mypage',id:'show')
              =link_to "変更する", user_cards_path(user_id:"mypage")

  = render 'shared/single-footer'

app/views/items/edit.html.haml
.single-wrapper.item-edit-page
  = render "/shared/single-header"
  .single-container
    .item-wrapper
      %h2.title 商品の情報を入力
      = form_with model: @item, html: {class: "item-new", multipart: true, method: "PATCH"}, local: true do |f|
        - if @item.errors.any?
          - @item.errors.full_messages.each do |message|
            = message
        %section.form-section.media-min
          .input-part
            %h3.input-part__title 出品画像
            %span.input-part__require 必須
            %p.input-part__details 最大10枚までアップロードできます
            -# TODO: ドラッグ&ドロップ、フォームの見た目動作
            -# いま=> アップロードformLv2、普通のフォーム10個展開、同時アップロード

            .image-upload-part#img_prev
              - @item.images.each_with_index do |image, i|
                = render partial: 'shared/upload-images', locals:{image: image, f: f, i: i}

            = f.label :image, class: "input-part__dropbox", id: "drop_zone" do
              .media-min__append--icon
                = f.file_field :image, class: 'hidden image-uploader', multiple: true
                .media-min__hidden
                  ドラッグアンドドロップ
                  %br
                  またはクリックしてファイルをアップロード

        %section.form-section
          .input-part
            = f.label "商品名", class: "input-part__title"
            %span.input-part__require 必須
            = f.text_field :name, class: "input-part__input", placeholder: "商品名（必須 40文字まで)"
          .input-part.space
            = f.label "商品の説明", class: "input-part__title"
            %span.input-part__require 必須
            = f.text_area :detail, class: "input-part__textarea textarea-default", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5"
        %section.form-section
          .flex-container
            .flex-container__left
              %h3.sell-sub-head 商品の詳細
            .flex-container__right
              .input-part
                = f.label "カテゴリー", class: "input-part__title"
                %span.input-part__require 必須
                - parents = @categories[0..12]
              .relative
                .icon-select
                = f.collection_select :parent_category_id, parents, :id, :name, {include_blank: true}, class: "input-part__select parent-category"
              - parents.each do |parent|
                .relative--hidden{id: "#{parent.id}-children-item"}
                  .icon-select
                  = f.collection_select :child_category_id, parent.children, :id, :name, {include_blank: true}, disabled:"disabled", class: "input-part__select child-category"
              - parents.each do |parent|
                - parent.children.each do |child|
                  .relative--hidden{id: "#{child.id}-grandchildren-item"}
                    .icon-select
                    = f.collection_select :grandchild_category_id, child.children, :id, :name, {include_blank: true}, disabled:"disabled", class: "input-part__select grandchild-category"
              -# .space.hidden
              -# .input-part
              -#   = f.label "サイズ", class: "input-part__title"
              -#   %span.input-part__require 必須
              -# .relative
              -#   .icon-select
              -#     -# TODO: 特定カテゴリ展開時のみ表示させる、連動した条件バリデーション。
              -#     -# = f.select :category_id, [["XXS以下", "153"], ["XS(SS)", "154"], ["S", "2"], ["M", "3"], ["L", "4"], ["XL(LL)", "5"], ["2XL(3L)", "155"], ["4XL(5L)以上", "157"], ["FREE SIZE", "7"]], {include_blank: true}, class: "input-part__select"
              -# .space.hidden
              -# .input-part
              -#   = f.label "ブランド", class: "input-part__title"
              -#   %span.input-part__option 任意
              -#   -# TODO: 特定カテゴリ展開時のみ表示させる。
              -#   -# = f.text_field :category_id, class: "input-part__input", placeholder: "例）シャネル", value: ""
              .input-part.space
                = f.label "商品の状態", class: "input-part__title"
                %span.input-part__require 必須
              .relative
                .icon-select
                  = f.select :condition, Item.conditions_i18n.keys.map {|k| [Item.conditions_i18n[k], k]}, {include_blank: true}, class: "input-part__select"
        %section.form-section
          .flex-container.media-min--clear
            .flex-container__left
              %h3.sell-sub-head 配送について
              =link_to "?", "#", class:"form-question"
            .flex-container__right
              .input-part
                = f.label "配送料の負担", class: "input-part__title"
                %span.input-part__require 必須
              .relative
                .icon-select
                  = f.select :delivery_cost, Item.delivery_costs_i18n.keys.map {|k| [Item.delivery_costs_i18n[k], k]}, {include_blank: true}, class: "input-part__select"
              .space.hidden
              .input-part.space
                = f.label "発送の方法", class: "input-part__title"
                %span.input-part__require 必須
              .relative
                .icon-select
                  = f.select :delivery_method, Item.delivery_methods_i18n.keys.map {|k| [Item.delivery_methods_i18n[k], k]}, {include_blank: true}, class: "input-part__select"
              .input-part.space
                = f.label "発送元の地域", class: "input-part__title"
                %span.input-part__require 必須
              .relative
                .icon-select
                  = f.select :delivery_prefecture, Item.delivery_prefectures_i18n.keys.map {|k| [Item.delivery_prefectures_i18n[k], k]}, {include_blank: true}, class: "input-part__select"
              .input-part.space
                = f.label "発送までの日数", class: "input-part__title"
                %span.input-part__require 必須
              .relative
                .icon-select
                  = f.select :delivery_day, Item.delivery_days_i18n.keys.map {|k| [Item.delivery_days_i18n[k], k]}, {include_blank: true}, class: "input-part__select"
        %section.form-section
          .flex-container
            .flex-container__left
              %h3.sell-sub-head 販売価格(300〜9,999,999)
              = link_to "?", "#", class:"form-question"
            .flex-container__right
              .input-part
                %ul.input-part__price
                  %li.input-part__price--bace.flex-container
                    .input-part__price--bace--left
                      = f.label "価格", class: "input-part__title"
                      %span.input-part__require 必須
                    .input-part__price--bace--right
                      %p.yen ¥
                      = f.text_field :price, class: "input-part__input", placeholder: "例）300", maxlength: "7"
                  %li.input-part__price--fee.border-top.flex-container
                    .input-part__price--fee--left 販売手数料 (10%)
                    .input-part__price--fee--right.input-part__price--fee--output= @item.price / 10

                  %li.input-part__price--total.border-top.flex-container
                    .input-part__price--total--left 販売利益
                    .input-part__price--fee--right.input-part__price--total--output= @item.price - (@item.price / 10)

        %section.form-section
          %p.notes
            = link_to "禁止されている出品", "#", class:"notes__link"
            = link_to "行為", "#"
            を必ずご確認ください。
          %p.notes
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            = link_to "偽ブランドの販売", "#", class:"notes__link"
            は犯罪であり処罰される可能性があります。
          %p.notes
            また、出品をもちまして
            = link_to "加盟店規約", "#", class:"notes__link"
            に同意したことになります。

          = f.submit "変更する", class: "submit-btn--red"
          = link_to "キャンセル", item_path(params[:id]), class: "submit-btn--gray"
        .overlay
  = render partial: "/shared/single-footer"

app/views/items/index.html.haml
.wrapper.index-page
  = render 'shared/header'

  %main
    %section.slick
      %figure.slick-list.slide01=image_tag "slider-01.png", alt: "スライダーの画像", class: "slick-list__image"
      %figure.slick-list.slide02=image_tag "slider-02.png", alt: "スライダーの画像", class: "slick-list__image"
      %figure.slick-list.slide03=image_tag "slider-03.png", alt: "スライダーの画像", class: "slick-list__image"

  %section.pick-up-container
    %h2.pick-up-container__header ピックアップカテゴリー
    %section.item-boxes
      %h3.item-boxes__header.text-center
        = link_to 'レディース 新着アイテム', src: '#'
      = render 'shared/items-box', items: @ladies_items
      .item-boxes__view-all
        =link_to '全ての商品を見る', src:'#'
    %section.item-boxes
      %h3.item-boxes__header.text-center
        = link_to 'メンズ 新着アイテム', src: '#'
      = render 'shared/items-box', items: @mens_items
      .item-boxes__view-all
        =link_to '全ての商品を見る', src:'#'
    %section.item-boxes
      %h3.item-boxes__header.text-center
        = link_to 'ベビー・キッズ 新着アイテム', src: '#'
      = render 'shared/items-box', items: @kids_items
      .item-boxes__view-all
        =link_to '全ての商品を見る', src:'#'
    %section.item-boxes
      %h3.item-boxes__header.text-center
        = link_to 'コスメ・香水・美容 新着アイテム', src: '#'
      = render 'shared/items-box', items: @cosme_items
      .item-boxes__view-all
        =link_to '全ての商品を見る', src:'#'

  = render 'shared/aside'
  = render 'shared/footer'
  = render 'shared/footer-sell-btn'

app/views/items/search.html.haml
- breadcrumb :search
%wrapper.search-page
  =render 'shared/header'
  = render 'shared/breadcrumb'

  .search-container
    .search-content-l
      .not-visible-in-full-width
        .nav
          .nav__content#sort
            %p.icon-sort
            =form_with url:'#' do |f|
              = f.select :sort_order, [["並び替え",""],["価格の安い順","01"],["価格の高い順","02"],["出品の古い順","03"],["出品の新しい順","04"],["いいね！の多い順","05"]], {}, class: "select-box__tablet"
          .nav__content
            %p.icon-search-plus#search
            %p.nav__content__message 詳細検索


      .visible-in-full-width
        -# フォームの中身はカテゴリー検索を実装される方が適宜変更ください
        =form_with url:'#' do |f|
          = f.select :sort_order, [["並び替え",""],["価格の安い順","01"],["価格の高い順","02"],["出品の古い順","03"],["出品の新しい順","04"],["いいね！の多い順","05"]], {}, class: "select-box__inner"
          .search-option
            %h3.search-option__header 詳細検索
            .options
              %h4.options__header.icon-plus キーワードを追加する
              = f.text_field :keyword, class:"text-field", placeholder: "今の検索キーワード"

              .select-box
                %h4.options__header.icon-list カテゴリーを選択する
                = f.select :categories, [["すべて",""],["カテゴリー１","01"],["カテゴリー２","02"],["カテゴリー３","03"],["カテゴリー４","04"],["カテゴリー５","05"]], {}, class: "select-box__inner"
                %p.icon-chevron-down

              %h4.options__header.icon-tag ブランド名から探す
              = f.text_field :keyword, class:"text-field", placeholder: "例）シャネル"

              .select-box
                %h4.options__header.icon-ruler サイズを指定する
                = f.select :categories, [["すべて",""],["オプション１","01"],["オプション２","02"],["オプション３","03"],["オプション４","04"],["オプション５","05"]], {}, class: "select-box__inner"
                %p.icon-chevron-down

              .select-box
                %h4.options__header.icon-coins 価格
                = f.select :categories, [["すべて",""],["オプション１","01"],["オプション２","02"],["オプション３","03"],["オプション４","04"],["オプション５","05"]], {}, class: "select-box__inner"
                %p.icon-chevron-down

              .options__price
                = f.text_field :keyword, class:"text-field", placeholder: "¥ Min"
                %span.options__price__range ~
                = f.text_field :keyword, class:"text-field", placeholder: "¥ Max"

              %h4.options__header.icon-star 商品の状態
              .check-box
                - %w(すべて 状態１ 状態２).each do |condition|
                  %label
                    = check_box_tag 'items[condition][]', condition
                    = condition

              %h4.options__header.icon-truck 配送料の負担
              .check-box
                - %w(すべて 着払い 送料込み).each do |ship_from|
                  %label
                    = check_box_tag 'items[ship_from][]', ship_from
                    = ship_from

              %h4.options__header.icon-cart 販売状況
              .check-box
                - %w(すべて 販売中 売り切れ).each do |buyer_id|
                  %label
                    = check_box_tag 'items[buyer_id][]', buyer_id
                    = buyer_id

              .btn-box
                = f.button "クリア", type: :reset, class: "btn-box__clear"
                = f.submit "完了", class: "btn-box__search"

    -# 右側のアイテムボックス一覧
    .search-content-r
      .result

        -if @items.count == 0 || params[:keyword].present? == false
          %h2.result__header="検索結果 0件"
          %p.result__message 該当する商品が見つかりません。商品は毎日増えていますので、これからの出品に期待してください。

          %h3.new-items 新着商品
          = render 'shared/items-box', items: @all_items

        - else

          %h2.result__header="検索結果１〜#{@items.count}件"
          .item-box__container
            = render 'shared/items-box', items: @items

  =render 'shared/aside'
  =render 'shared/footer'
  =render 'shared/footer-sell-btn'

app/views/items/show.html.haml
- breadcrumb :item
= render 'shared/header'
= render 'shared/breadcrumb'
.item-detail-page
  %main.single-container
    .panel
      %h2.panel__head
        = @item.name
      .item-info
        .item-info__photo
          -if @item.status == "soldout"
            .soldout-color
            .soldout
          %section.slider
            - @item.images.each do |image|
              %figure.slider__list= image_tag image.image.url, class: "slider__list__image"

          %section.thumb
            - @item.images[0..4].each do |image|
              %figure.thumb__list= image_tag image.image.url, class: "thumb__list__image"

          -if @item.images.length >= 6
            %section.thumb
              - @item.images[5..9].each do |image|
                %figure.thumb__list= image_tag image.image.url, class: "thumb__list__image"


      .visible-sp-only
        .item-info
          .item-info__price
            %p
              = "￥#{@item.price}"
              %span.item-info__price__tax (税込)
              %span.item-info__price__shipping= @item.delivery_cost_i18n

          - if user_signed_in? && @item.status != "soldout"
            .sales-message
              ="売上金#{current_user.money}円をお持ちです"
          - if @item.status == "soldout"
            .sold-out-btn 売り切れました
          - else
            .buy-btn
              = link_to "購入画面に進む", confirm_item_path(params[:id])
      %table.detail-info
        %tbody
          %tr
            %th 出品者
            %td.detail-info__nickname.detail_link
              =link_to "#{@item.users[0].name}",'#'
              .detail-info__ratings
                %p.icon-good
                %span 106
                %p.icon-normal
                %span 2
                %p.icon-bad
                %span 0
          %tr
            %th カテゴリー
            %td.detail-info__category
              - if @item.category.has_parent? && @item.category.parent.has_parent?
                %p.detail_link
                  =link_to @item.category.parent.parent.name, category_path(id: @item.category.parent.parent.id)
                %p.icon-arrow-right.detail_link
                  =link_to @item.category.parent.name, category_path(id: @item.category.parent.id)
                %p.icon-arrow-right.detail_link
                  =link_to @item.category.name, category_path(id: @item.category.id)
              - elsif @item.category.has_parent?
                %p.detail_link
                  =link_to @item.category.parent.name, category_path(id: @item.category.parent.id)
                %p.icon-arrow-right.detail_link
                  =link_to @item.category.name, category_path(id: @item.category.id)
              - else
                %p.detail_link
                  =link_to @item.category.name, category_path(id: @item.category.id)
          %tr
            %th ブランド
            %td.detail-info__brand
              %p.detail_link
                =link_to 'シャネル', '#' #ブランド名 カテゴリーは実装しない
          %tr
            %th 商品の状態
            %td
              = @item.condition_i18n
          %tr
            %th 配送料の負担
            %td
              = @item.delivery_cost_i18n
          %tr
            %th 配送の方法
            %td
              = @item.delivery_method_i18n
          %tr
            %th 配送元地域
            %td
              %p.detail_link
                =link_to "#{@item.delivery_prefecture_i18n}", '#'
          %tr
            %th 発送日の目安
            %td
              =@item.delivery_day_i18n
      .item-info
        .item-info__price
          %p
            = "￥#{@item.price}"
            %span.item-info__price__tax (税込)
            %span.item-info__price__shipping= @item.delivery_cost_i18n

        - if user_signed_in? && @item.status != "soldout"
          .sales-message
            ="売上金#{current_user.money}円をお持ちです"
        - if @item.status == "soldout"
          .sold-out-btn 売り切れました
        - else
          .buy-btn
            = link_to "購入画面に進む", confirm_item_path(params[:id])

      .item-info__description
        %p
          = @item.detail

      .like-report
        %button.like-report__btn
          %p.icon-like いいね！ 10
        %button.like-report__btn
          %p.icon-report 不適切な商品の報告
        %p.icon-lock.trial-to-safe=link_to 'あんしん・あんぜんへの取り組み', '#'

  - if user_signed_in? && current_user.id == @item.users[0].id && @item.status != "soldout"
    .myItem-container
      .myItem-container__inner
        %button.edit-item__btn=link_to "商品の編集", edit_item_path
        %p or
        %button.suspend-item__btn=link_to "出品を一時停止する", '#'
        %button.delete-item__btn#modal-open この商品を削除する

    .modal-overlay
      #modal-window.modal
        .modal__inner--top
          .alert
            %h3.alert__header 確認
            %p.alert__message
              削除すると二度と復活できません
              %br 削除する代わりに停止することもできます

            %p.alert__message 本当に削除しますか？
        .modal__inner--bottom
          %ul.delete-choice
            %li.delete-choice__cancel
              %p#close-modal キャンセル
            %li.delete-choice__delete
              =link_to "削除する", item_path(@item.id), method: :delete, id: "close-modal"
  %ul.other-item
    %li.other-item__previous.icon-arrow-l 前の商品
    %li.other-item__next.icon-arrow-r 次の商品

  .sns-wrapper
    .sns-wrapper__icon.icon-facebook
    .sns-wrapper__icon.icon-twitter
    .sns-wrapper__icon.icon-line
    .sns-wrapper__icon.icon-pinterest

  %section.pick-up-container
    %h2.pick-up-container__header
      ="#{@item.users[0].name}さんのその他の出品"
    = render 'shared/items-box', items: @same_user_items

  %section.pick-up-container
    %h2.pick-up-container__header
      = @item.category.name
      のその他の商品

    = render 'shared/items-box', items: @same_category_items
= render 'shared/footer'