config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  root 'items#index'
  get 'edit' => 'users#edit'

  resources :users, only: [:show, :new, :edit, :update] do
    resources :cards, only: [:index, :new] do
      # cards controllerはモデルを持たない。データはpayjpに格納
      member do
        get 'pay' #カード決済アクション
        get 'card_delete'
        get 'card_new' #カード登録アクション(newとは違いviewを持たない)
      end
    end
    collection do
      get 'signup/:url',action: 'new'
      get 'mypage/:url',action: 'edit'
    end
  end

  resources :items do
    member do
      get 'confirm' #購入確認画面
    end
    collection do
      get 'search'
    end
    resources :categories, only: [:search]
  end

  resources :categories, only: :show
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_categories
  before_action :authenticate_user!
  before_action :set_item, only:[:pay]
  require 'payjp'

  def index #クレジットカード情報表示
    Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]
    customer = Payjp::Customer.retrieve(current_user.payjp_id)
    if customer.default_card
      default_card = customer.default_card
      @card = customer.cards.retrieve(default_card)
    end
  end

  def card_new #クレジットカード登録
    Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]
    customer = Payjp::Customer.retrieve(current_user.payjp_id)
    customer.cards.create(card: params[:payjp_token])
    redirect_to user_cards_path(user_id:"mypage")
  rescue => e
    redirect_to new_user_card_path(user_id:"mypage")
  end

  def card_delete #カード情報削除
    Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]
    customer = Payjp::Customer.retrieve(current_user.payjp_id)
    default_card = customer.default_card
    card = customer.cards.retrieve(default_card)
    card.delete
    redirect_to user_cards_path(user_id: 'mypage')
  rescue => e #エラーハンドリング
    redirect_to user_cards_path(user_id: 'mypage')
  end

  def pay #カード支払い / Itemにbuyer_idを追加、statusを変更
    begin
      Payjp.api_key = Rails.application.credentials.payjp[:secret_access_key]
      customer = Payjp::Customer.retrieve(current_user.payjp_id)
      default_card = customer.default_card
      card = customer.cards.retrieve(default_card)
      charge = Payjp::Charge.create(
        amount: @item.price,
        customer: customer,
        currency: 'jpy',
      )
      @item.update(buyer_id: current_user.id, status:2)
      redirect_to root_path
    rescue => e #エラーハンドリング
      redirect_to root_path
    end
  end


  def set_item
    @item = Item.find(params[:id])
  end
end

app/views/cards/index.html.haml
- breadcrumb :card
%wrapper.card-page
  =render 'shared/header'
  = render 'shared/breadcrumb'

  .two-column-container
    .two-column-container__r
      .panel
        %h2.panel__head 支払い方法
        %section.panel__inner
          %h3.panel__inner__head クレジットカード一覧
          - if @card.present?
            .card-info
              - case
                -when @card.brand == "Visa" 
                  =image_tag 'visa_logo.png', width:"49", height:"20", alt:"visa"
                -when @card.brand == "MasterCard"
                  =image_tag 'mastercard_logo.png', width:"49", height:"20", alt:"visa"
              %p.card-info__num 
                = "**** **** **** #{@card.last4}"
              %p.card-info__date
                = "#{@card.exp_month} / #{@card.exp_year}"
              %button.card-info__delete-btn
                = link_to '削除する', card_delete_user_card_path(user_id:'mypage', id:'1')
              -# = button_to "削除", { :action => "destroy", :id => @card.id }, :confirm => "本当に削除しますか?", :method => :delete
              -# サーバーサイドが整ったらコメントアウトを外す
          - else
            .card-info
              %button.card-info__add-btn
                =link_to new_user_card_path do
                  .icon-card
                  %p クレジットカードを追加する

        .bottom-info
          %p.bottom-info__link.icon-arrow-r=link_to "支払い方法について" , '#'
    = render 'shared/mypage-nav'
=render 'shared/footer-sell-btn'

app/views/cards/new.html.haml
- breadcrumb :new_card
.wrapper.card-create-page
  = render 'shared/header'
  = render 'shared/breadcrumb'

  .two-column-container
    .two-column-container__r
      .registration
        .panel
          %h2.panel__head 支払い方法
          .panel__inner
            = form_with url:card_new_user_card_path(user_id:'mypage',id:'1'), html:{method:'GET', class:"charge-form"}  do |f|
              .content
                .form-group
                  = f.label "カード番号", class:"form-group__label"
                  %span.form-group__require 必須
                  = f.text_field :number, class:"form-group__input",name:"number", id:"payment-card-number", placeholder: "半角数字のみ", maxlength: "16"
                  .form-group__card-logos
                    = image_tag 'visa_logo.png', height:'20px'
                    = image_tag 'mastercard_logo.png', height:'20px'
                    = image_tag 'saison_logo.png', height:'20px'
                .form-group
                  = f.label "有効期限", class:"form-group__label"
                  %span.form-group__require 必須
                  .form-group__expiration-wrap
                    = f.select :exp_month, [["--",""],["1","01"],["2","02"],["3","03"],["4","04"],["5","05"],["6","06"],["7","07"],["8","08"],["9","09"],["10","10"],["11","11"],["12","12"]],{}, {class:"exp-month" ,id:"payment-card-exp-month", name:"exp_month"}
                    .icon-chevron-bottom
                    %span 月
                  .form-group__expiration-wrap
                    = f.select :exp_year, [["--",""],["19","2019"],["20","2020"],["21","2021"],["22","2022"],["23","2023"],["24","2024"],["25","2025"],["26","2026"],["27","2027"],["28","2028"],["29","2029"],],{},{class:"exp-year", id:"payment-card-exp-year", name:"exp-year"}
                    %span 年
                    .icon-chevron-bottom
                .form-group
                  = f.label "セキュリティコード", class:"form-group__label"
                  %span.form-group__require 必須
                  = f.text_field :cvc, class:"form-group__input",id:"payment-card-cvc", name:"cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4"
                  .form-group__card-info
                    .icon-question-circle
                    =link_to "カード裏面の番号とは？", src:"#", class:"icon-chevron-right"
                  %p= f.submit "追加する", class: "card-registration-btn"

    = render 'shared/mypage-nav'
    = render 'shared/footer-sell-btn'